### ISSUE TITLE
Allow key remapping

### ISSUE THREAD

**Issue by ComputerSmoke** [Inspirateur/riverbed#38]
Players should eventually be able to view and change their keybinds via a gui. These keybinds should persist between sessions.

For development purposes it makes sense to load keybinds from a settings file, which is untracked by git and a default of which is generated when none exists. This will allow devs to use alternative keymaps without affecting upstream. 

(the default keybinds don't entirely work with my keyboard.)

**Comment by Inspirateur** [comment]
Done :)
